In [1]:
[[23,12,123,12,33],[],[]]

[[23, 12, 123, 12, 33], [], []]

In [4]:
import numpy
n=numpy.arange(27)

In [6]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [8]:
type(n)

numpy.ndarray

In [11]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [13]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
import cv2

In [7]:
im_g=cv2.imread('smallgray.png',0)

In [9]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
im_g=cv2.imread('smallgray.png',1) #BGR layers 3 dimensional array
im_g   # the group is the BGR -- # the list in the group is the column -- #the items in the list is number of rows

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [13]:
cv2.imwrite('newsmallgray.png',im_g)

True

In [15]:
im_g=cv2.imread('smallgray.png',0)

In [18]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [20]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
for i in im_g:
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
for i in im_g.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [26]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [32]:
import numpy
ims=numpy.hstack((im_g,im_g))
ims #combine arrays together

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
lst=numpy.hsplit(ims,5)
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]